<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net6.0-windows</TargetFramework>
    <OutputType>WinExe</OutputType>
    <LangVersion>latest</LangVersion>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <UseWindowsForms>true</UseWindowsForms>
    <ImportWindowsDesktopTargets>true</ImportWindowsDesktopTargets>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="System.ComponentModel" />
    <Reference Include="System.Configuration.Install" />
    <Reference Include="System.Transactions" />
  </ItemGroup>
  <ItemGroup>
    <Content Include="ServiceUtility\.vs\ServieUtility\v17\.suo" />
    <Content Include="ServiceUtility\.vs\slnx.sqlite" />
    <Content Include="ServiceUtility\.vs\VSWorkspaceState.json" />
  </ItemGroup>
  <ItemGroup>
    <Folder Include="DataAnalytics" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Core.System.Configuration.Install" Version="1.1.0" />
    <PackageReference Include="Microsoft.CSharp" Version="4.7.0" />
    <PackageReference Include="MySql.Data" Version="8.0.28" />
    <PackageReference Include="System.ComponentModel.Annotations" Version="5.0.0" />
    <PackageReference Include="System.Data.DataSetExtensions" Version="4.5.0" />
    <PackageReference Include="Microsoft.DotNet.UpgradeAssistant.Extensions.Default.Analyzers" Version="0.3.310801">
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.Windows.Compatibility" Version="6.0.0" />
  </ItemGroup>
  <ItemGroup>
    <Compile Remove="DataAnalytics\SalesReportForm.cs" />
    <Compile Remove="DataAnalytics\SalesReportForm.Designer.cs" />
    <EmbeddedResource Remove="DataAnalytics\SalesReportForm.resx" />
  </ItemGroup>
</Project>