//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Better_Limited_Project.StaffUtility {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class StaffUtilityStringResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StaffUtilityStringResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Better_Limited_Project.StaffUtility.StaffUtilityStringResources", typeof(StaffUtilityStringResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New password does not meet requirement! Passwords must consist of at least 8 characters of a combination of English character and/or numbers..
        /// </summary>
        internal static string ChangePasswordForm_btnApply_Click_New_password_does_not_meet_requirement__Passwords_must_consist_of_at_least_8_characters_of_a_combination_of_English_character_and_or_numbers_ {
            get {
                return ResourceManager.GetString("ChangePasswordForm_btnApply_Click_New_password_does_not_meet_requirement__Passwor" +
                        "ds_must_consist_of_at_least_8_characters_of_a_combination_of_English_character_a" +
                        "nd_or_numbers_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current staff does not have an account..
        /// </summary>
        internal static string no_staff_account_when_try_to_change_password {
            get {
                return ResourceManager.GetString("no staff account when try to change password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please fill in all fields!.
        /// </summary>
        internal static string not_all_fields_filled {
            get {
                return ResourceManager.GetString("not all fields filled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passowrd does not meet requirement. Passwords must consist of at least 8 characters of a combination of English character and/or numbers..
        /// </summary>
        internal static string password_not_valid {
            get {
                return ResourceManager.GetString("password not valid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Re-entered password does not match! Please retry!.
        /// </summary>
        internal static string reentered_password_dont_match {
            get {
                return ResourceManager.GetString("reentered password dont match", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title &quot;{0}&quot; does not match department &quot;{1}&quot;. Please reselect the title/department..
        /// </summary>
        internal static string selected_department_title_dont_match {
            get {
                return ResourceManager.GetString("selected department title dont match", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username &quot;{0}&quot; has been taken. Please choose another one..
        /// </summary>
        internal static string username_not_unique {
            get {
                return ResourceManager.GetString("username not unique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username &quot;{0}&quot; is not valid. Usernames must consist of at least 4 characters of a combination of English character and/or numbers..
        /// </summary>
        internal static string username_not_valid {
            get {
                return ResourceManager.GetString("username not valid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not chosen.
        /// </summary>
        internal static string workplace_not_chosen {
            get {
                return ResourceManager.GetString("workplace not chosen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong password!.
        /// </summary>
        internal static string wrong_password {
            get {
                return ResourceManager.GetString("wrong password", resourceCulture);
            }
        }
    }
}
