//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Better_Limited_Project.Sales.PaymentUtility {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class PaymentStringResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PaymentStringResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Better_Limited_Project.Sales.PaymentUtility.PaymentStringResources", typeof(PaymentStringResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current sales order has requested for a delivery.
        ///Confirm removing delivery request?.
        /// </summary>
        internal static string askRemoveDeliveryRequest {
            get {
                return ResourceManager.GetString("askRemoveDeliveryRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current sales order has not requested for a delivery.
        ///Confirm sending a delivery request for this order?.
        /// </summary>
        internal static string askSendDeliveryRequest {
            get {
                return ResourceManager.GetString("askSendDeliveryRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The delivery request has already been confirmed by the inventory department. Removal failed..
        /// </summary>
        internal static string cant_remove_delivery_request {
            get {
                return ResourceManager.GetString("cant remove delivery request", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are currently no completed product payments. (To see deposit receipts, click the button on the right.).
        /// </summary>
        internal static string cantViewPaymentReceipt {
            get {
                return ResourceManager.GetString("cantViewPaymentReceipt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To request for a delivery, customer&apos;s information is needed.
        ///Start creating a customer record?.
        /// </summary>
        internal static string create_customer_information_to_request_delivery {
            get {
                return ResourceManager.GetString("create customer information to request delivery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delivery request sent..
        /// </summary>
        internal static string deliveryRequestSent {
            get {
                return ResourceManager.GetString("deliveryRequestSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file is currently being used by another process..
        /// </summary>
        internal static string FileBeingUsedByAnotherProcess {
            get {
                return ResourceManager.GetString("FileBeingUsedByAnotherProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please pay enough cash..
        /// </summary>
        internal static string notEnoughCashPaid {
            get {
                return ResourceManager.GetString("notEnoughCashPaid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a delivery session!.
        /// </summary>
        internal static string pleaseSelectDeliverySession {
            get {
                return ResourceManager.GetString("pleaseSelectDeliverySession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Delivery Request.
        /// </summary>
        internal static string removeDeliveryRequest {
            get {
                return ResourceManager.GetString("removeDeliveryRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This delivery has already been confirmed by inventory department.
        ///Delivery request removal failed..
        /// </summary>
        internal static string removeDeliveryRequestFail {
            get {
                return ResourceManager.GetString("removeDeliveryRequestFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send Delivery Request.
        /// </summary>
        internal static string sendDeliveryRequest {
            get {
                return ResourceManager.GetString("sendDeliveryRequest", resourceCulture);
            }
        }
    }
}
