//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Better_Limited_Project.ProductUtility.ProductList.Forms {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ProductList {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ProductList() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Better_Limited_Project.ProductUtility.ProductList.Forms.ProductList", typeof(ProductList).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply.
        /// </summary>
        internal static string btnApply_Text {
            get {
                return ResourceManager.GetString("btnApply.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string btnCancel_Text {
            get {
                return ResourceManager.GetString("btnCancel.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose Image.
        /// </summary>
        internal static string btnChooseImage_Text {
            get {
                return ResourceManager.GetString("btnChooseImage.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        internal static string btnCreate_Text {
            get {
                return ResourceManager.GetString("btnCreate.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Description.
        /// </summary>
        internal static string btnEditDescription_Text {
            get {
                return ResourceManager.GetString("btnEditDescription.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Product.
        /// </summary>
        internal static string btnNewProductClicked_Text {
            get {
                return ResourceManager.GetString("btnNewProductClicked.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Product.
        /// </summary>
        internal static string btnRemoveProduct_Text {
            get {
                return ResourceManager.GetString("btnRemoveProduct.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restock.
        /// </summary>
        internal static string btnRestock_Text {
            get {
                return ResourceManager.GetString("btnRestock.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload Image.
        /// </summary>
        internal static string btnUpdateImage_Text {
            get {
                return ResourceManager.GetString("btnUpdateImage.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Info.
        /// </summary>
        internal static string btnUpdateInfo_Text {
            get {
                return ResourceManager.GetString("btnUpdateInfo.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Info.
        /// </summary>
        internal static string btnUpdateInfo_Text1 {
            get {
                return ResourceManager.GetString("btnUpdateInfo.Text1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Product Info.
        /// </summary>
        internal static string btnUpdateProductInfo_Text {
            get {
                return ResourceManager.GetString("btnUpdateProductInfo.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Selling Price.
        /// </summary>
        internal static string btnUpdateSellingPrice_Text {
            get {
                return ResourceManager.GetString("btnUpdateSellingPrice.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        internal static string category_HeaderText {
            get {
                return ResourceManager.GetString("category.HeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *.
        /// </summary>
        internal static string label1_Text {
            get {
                return ResourceManager.GetString("label1.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Image.
        /// </summary>
        internal static string label1_Text1 {
            get {
                return ResourceManager.GetString("label1.Text1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name:.
        /// </summary>
        internal static string label1_Text2 {
            get {
                return ResourceManager.GetString("label1.Text2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name:.
        /// </summary>
        internal static string label1_Text3 {
            get {
                return ResourceManager.GetString("label1.Text3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Name:.
        /// </summary>
        internal static string label2_Text {
            get {
                return ResourceManager.GetString("label2.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *.
        /// </summary>
        internal static string label3_Text {
            get {
                return ResourceManager.GetString("label3.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *.
        /// </summary>
        internal static string label4_Text {
            get {
                return ResourceManager.GetString("label4.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *.
        /// </summary>
        internal static string label5_Text {
            get {
                return ResourceManager.GetString("label5.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *.
        /// </summary>
        internal static string label6_Text {
            get {
                return ResourceManager.GetString("label6.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category:.
        /// </summary>
        internal static string lblCategory_Text {
            get {
                return ResourceManager.GetString("lblCategory.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category:.
        /// </summary>
        internal static string lblCategory_Text1 {
            get {
                return ResourceManager.GetString("lblCategory.Text1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category:.
        /// </summary>
        internal static string lblCategory_Text2 {
            get {
                return ResourceManager.GetString("lblCategory.Text2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter By Category.
        /// </summary>
        internal static string lblCategoryFilter_Text {
            get {
                return ResourceManager.GetString("lblCategoryFilter.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Description:.
        /// </summary>
        internal static string lblDescription_Text {
            get {
                return ResourceManager.GetString("lblDescription.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Description.
        /// </summary>
        internal static string lblDescription_Text1 {
            get {
                return ResourceManager.GetString("lblDescription.Text1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Product Description.
        /// </summary>
        internal static string lblHeader_Text {
            get {
                return ResourceManager.GetString("lblHeader.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Information.
        /// </summary>
        internal static string lblHeader_Text1 {
            get {
                return ResourceManager.GetString("lblHeader.Text1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Update.
        /// </summary>
        internal static string lblHeader_Text2 {
            get {
                return ResourceManager.GetString("lblHeader.Text2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Update.
        /// </summary>
        internal static string lblHeader_Text3 {
            get {
                return ResourceManager.GetString("lblHeader.Text3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Image:.
        /// </summary>
        internal static string lblImage_Text {
            get {
                return ResourceManager.GetString("lblImage.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name:.
        /// </summary>
        internal static string lblName_Text {
            get {
                return ResourceManager.GetString("lblName.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Category:.
        /// </summary>
        internal static string lblNewCategory_Text {
            get {
                return ResourceManager.GetString("lblNewCategory.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Info.
        /// </summary>
        internal static string lblNewInfo_Text {
            get {
                return ResourceManager.GetString("lblNewInfo.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Info.
        /// </summary>
        internal static string lblNewInfo_Text1 {
            get {
                return ResourceManager.GetString("lblNewInfo.Text1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Name:.
        /// </summary>
        internal static string lblNewName_Text {
            get {
                return ResourceManager.GetString("lblNewName.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Orginal Price:.
        /// </summary>
        internal static string lblNewOriginalPrice_Text {
            get {
                return ResourceManager.GetString("lblNewOriginalPrice.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phasing-out:.
        /// </summary>
        internal static string lblNewPhasingOut_Text {
            get {
                return ResourceManager.GetString("lblNewPhasingOut.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Product.
        /// </summary>
        internal static string lblNewProduct_Text {
            get {
                return ResourceManager.GetString("lblNewProduct.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Reorder Level:.
        /// </summary>
        internal static string lblNewReorderLevel_Text {
            get {
                return ResourceManager.GetString("lblNewReorderLevel.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Reorder Level:.
        /// </summary>
        internal static string lblNewReorderLevel_Text1 {
            get {
                return ResourceManager.GetString("lblNewReorderLevel.Text1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Selling Price:.
        /// </summary>
        internal static string lblNewSellingPrice_Text {
            get {
                return ResourceManager.GetString("lblNewSellingPrice.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Selling Price:.
        /// </summary>
        internal static string lblNewSellingPrice_Text1 {
            get {
                return ResourceManager.GetString("lblNewSellingPrice.Text1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Selling Price (HKD$).
        /// </summary>
        internal static string lblNewSellingPrice_Text2 {
            get {
                return ResourceManager.GetString("lblNewSellingPrice.Text2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Stock Level:.
        /// </summary>
        internal static string lblNewStockLevel_Text {
            get {
                return ResourceManager.GetString("lblNewStockLevel.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Stock Level:.
        /// </summary>
        internal static string lblNewStockLevel_Text1 {
            get {
                return ResourceManager.GetString("lblNewStockLevel.Text1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Supplier:.
        /// </summary>
        internal static string lblNewSuplier_Text {
            get {
                return ResourceManager.GetString("lblNewSuplier.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Original Info.
        /// </summary>
        internal static string lblOriginalInfo_Text {
            get {
                return ResourceManager.GetString("lblOriginalInfo.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Original Info.
        /// </summary>
        internal static string lblOriginalInfo_Text1 {
            get {
                return ResourceManager.GetString("lblOriginalInfo.Text1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Selling Price.
        /// </summary>
        internal static string lblOriginalInfo_Text2 {
            get {
                return ResourceManager.GetString("lblOriginalInfo.Text2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Original Price:.
        /// </summary>
        internal static string lblOriginalPrice_Text {
            get {
                return ResourceManager.GetString("lblOriginalPrice.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Original Price:.
        /// </summary>
        internal static string lblOriginalPrice_Text1 {
            get {
                return ResourceManager.GetString("lblOriginalPrice.Text1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Original Price:.
        /// </summary>
        internal static string lblOriginalPrice_Text2 {
            get {
                return ResourceManager.GetString("lblOriginalPrice.Text2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Original Selling Price:.
        /// </summary>
        internal static string lblOriginalSellingPrice_Text {
            get {
                return ResourceManager.GetString("lblOriginalSellingPrice.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phasing-out:.
        /// </summary>
        internal static string lblPhasingOut_Text {
            get {
                return ResourceManager.GetString("lblPhasingOut.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price:.
        /// </summary>
        internal static string lblPrice_Text {
            get {
                return ResourceManager.GetString("lblPrice.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Information.
        /// </summary>
        internal static string lblProductInfo_Text {
            get {
                return ResourceManager.GetString("lblProductInfo.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity in Storage:.
        /// </summary>
        internal static string lblQuantity_Text {
            get {
                return ResourceManager.GetString("lblQuantity.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reorder Level:.
        /// </summary>
        internal static string lblReorderLevel_Text {
            get {
                return ResourceManager.GetString("lblReorderLevel.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reorder Level:.
        /// </summary>
        internal static string lblReorderLevel_Text1 {
            get {
                return ResourceManager.GetString("lblReorderLevel.Text1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reorder Level:.
        /// </summary>
        internal static string lblReorderLevel_Text2 {
            get {
                return ResourceManager.GetString("lblReorderLevel.Text2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search by Product Name/Supplier.
        /// </summary>
        internal static string lblSearchBox_Text {
            get {
                return ResourceManager.GetString("lblSearchBox.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selling Price:.
        /// </summary>
        internal static string lblSellingPrice_Text {
            get {
                return ResourceManager.GetString("lblSellingPrice.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selling Price:.
        /// </summary>
        internal static string lblSellingPrice_Text1 {
            get {
                return ResourceManager.GetString("lblSellingPrice.Text1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selling Price:.
        /// </summary>
        internal static string lblSellingPrice_Text2 {
            get {
                return ResourceManager.GetString("lblSellingPrice.Text2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stock Level:.
        /// </summary>
        internal static string lblStockLevel_Text {
            get {
                return ResourceManager.GetString("lblStockLevel.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stock Level:.
        /// </summary>
        internal static string lblStockLevel_Text1 {
            get {
                return ResourceManager.GetString("lblStockLevel.Text1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supplier:.
        /// </summary>
        internal static string lblSupplier_Text {
            get {
                return ResourceManager.GetString("lblSupplier.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supplier:.
        /// </summary>
        internal static string lblSupplier_Text1 {
            get {
                return ResourceManager.GetString("lblSupplier.Text1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email:.
        /// </summary>
        internal static string lblSupplierEmail_Text {
            get {
                return ResourceManager.GetString("lblSupplierEmail.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supplier Information.
        /// </summary>
        internal static string lblSupplierInFo_Text {
            get {
                return ResourceManager.GetString("lblSupplierInFo.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name:.
        /// </summary>
        internal static string lblSupplierName_Text {
            get {
                return ResourceManager.GetString("lblSupplierName.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone:.
        /// </summary>
        internal static string lblSupplierPhone_Text {
            get {
                return ResourceManager.GetString("lblSupplierPhone.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Retail Store/Warehouse.
        /// </summary>
        internal static string lblWorkplaceSelect_Text {
            get {
                return ResourceManager.GetString("lblWorkplaceSelect.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string name_HeaderText {
            get {
                return ResourceManager.GetString("name.HeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please fill all fields!.
        /// </summary>
        internal static string newProductNotAllFieldsFilled {
            get {
                return ResourceManager.GetString("newProductNotAllFieldsFilled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product and stock information updated..
        /// </summary>
        internal static string productAndStockUpdated {
            get {
                return ResourceManager.GetString("productAndStockUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Qty.
        /// </summary>
        internal static string quantity_HeaderText {
            get {
                return ResourceManager.GetString("quantity.HeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Off.
        /// </summary>
        internal static string rbPhasingOutOff_Text {
            get {
                return ResourceManager.GetString("rbPhasingOutOff.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Off.
        /// </summary>
        internal static string rbPhasingOutOff_Text1 {
            get {
                return ResourceManager.GetString("rbPhasingOutOff.Text1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On.
        /// </summary>
        internal static string rbPhasingOutOn_Text {
            get {
                return ResourceManager.GetString("rbPhasingOutOn.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On.
        /// </summary>
        internal static string rbPhasingOutOn_Text1 {
            get {
                return ResourceManager.GetString("rbPhasingOutOn.Text1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selling Price.
        /// </summary>
        internal static string selling_price_HeaderText {
            get {
                return ResourceManager.GetString("selling_price.HeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please fill in the product name!.
        /// </summary>
        internal static string updateProductNameNotFilled {
            get {
                return ResourceManager.GetString("updateProductNameNotFilled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name &quot;{0}&quot; already exists. Please choose another one..
        /// </summary>
        internal static string updateProductNameNotUnique {
            get {
                return ResourceManager.GetString("updateProductNameNotUnique", resourceCulture);
            }
        }
    }
}
