//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Better_Limited_Project.Login {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LoginForm_zh_HK {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LoginForm_zh_HK() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Better_Limited_Project.Login.LoginForm.zh-HK", typeof(LoginForm_zh_HK).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 登入.
        /// </summary>
        internal static string btnLogin_Text {
            get {
                return ResourceManager.GetString("btnLogin.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=311,Y=280}.
        /// </summary>
        internal static System.Drawing.Point lblLoginFailedMessage_Location {
            get {
                object obj = ResourceManager.GetObject("lblLoginFailedMessage.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=175, Height=16}.
        /// </summary>
        internal static System.Drawing.Size lblLoginFailedMessage_Size {
            get {
                object obj = ResourceManager.GetObject("lblLoginFailedMessage.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=347,Y=247}.
        /// </summary>
        internal static System.Drawing.Point lblPassword_Location {
            get {
                object obj = ResourceManager.GetObject("lblPassword.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Windows.Forms.RightToLeft similar to Yes.
        /// </summary>
        internal static System.Windows.Forms.RightToLeft lblPassword_RightToLeft {
            get {
                object obj = ResourceManager.GetObject("lblPassword.RightToLeft", resourceCulture);
                return ((System.Windows.Forms.RightToLeft)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=31, Height=13}.
        /// </summary>
        internal static System.Drawing.Size lblPassword_Size {
            get {
                object obj = ResourceManager.GetObject("lblPassword.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 密碼.
        /// </summary>
        internal static string lblPassword_Text {
            get {
                return ResourceManager.GetString("lblPassword.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=311,Y=201}.
        /// </summary>
        internal static System.Drawing.Point lblUsername_Location {
            get {
                object obj = ResourceManager.GetObject("lblUsername.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Windows.Forms.RightToLeft similar to Yes.
        /// </summary>
        internal static System.Windows.Forms.RightToLeft lblUsername_RightToLeft {
            get {
                object obj = ResourceManager.GetObject("lblUsername.RightToLeft", resourceCulture);
                return ((System.Windows.Forms.RightToLeft)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=67, Height=13}.
        /// </summary>
        internal static System.Drawing.Size lblUsername_Size {
            get {
                object obj = ResourceManager.GetObject("lblUsername.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 使用者名稱.
        /// </summary>
        internal static string lblUsername_Text {
            get {
                return ResourceManager.GetString("lblUsername.Text", resourceCulture);
            }
        }
    }
}
