//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Better_Limited_Project.Login {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    partial class LoginForm {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Better_Limited_Project.Login.LoginForm", typeof(LoginForm).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Font similar to [Font: Name=Noto Sans, Size=15.75, Units=3, GdiCharSet=1, GdiVerticalFont=False].
        /// </summary>
        internal static System.Drawing.Font btnLogin_Font {
            get {
                object obj = ResourceManager.GetObject("btnLogin.Font", resourceCulture);
                return ((System.Drawing.Font)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=334,Y=311}.
        /// </summary>
        internal static System.Drawing.Point btnLogin_Location {
            get {
                object obj = ResourceManager.GetObject("btnLogin.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=149, Height=44}.
        /// </summary>
        internal static System.Drawing.Size btnLogin_Size {
            get {
                object obj = ResourceManager.GetObject("btnLogin.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 4.
        /// </summary>
        internal static int btnLogin_TabIndex {
            get {
                object obj = ResourceManager.GetObject("btnLogin.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log In.
        /// </summary>
        internal static string btnLogin_Text {
            get {
                return ResourceManager.GetString("btnLogin.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Windows.Forms.ImeMode similar to NoControl.
        /// </summary>
        internal static System.Windows.Forms.ImeMode lblLoginFailedMessage_ImeMode {
            get {
                object obj = ResourceManager.GetObject("lblLoginFailedMessage.ImeMode", resourceCulture);
                return ((System.Windows.Forms.ImeMode)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=349,Y=280}.
        /// </summary>
        internal static System.Drawing.Point lblLoginFailedMessage_Location {
            get {
                object obj = ResourceManager.GetObject("lblLoginFailedMessage.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Windows.Forms.RightToLeft similar to Yes.
        /// </summary>
        internal static System.Windows.Forms.RightToLeft lblLoginFailedMessage_RightToLeft {
            get {
                object obj = ResourceManager.GetObject("lblLoginFailedMessage.RightToLeft", resourceCulture);
                return ((System.Windows.Forms.RightToLeft)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=137, Height=16}.
        /// </summary>
        internal static System.Drawing.Size lblLoginFailedMessage_Size {
            get {
                object obj = ResourceManager.GetObject("lblLoginFailedMessage.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 5.
        /// </summary>
        internal static int lblLoginFailedMessage_TabIndex {
            get {
                object obj = ResourceManager.GetObject("lblLoginFailedMessage.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Message).
        /// </summary>
        internal static string lblLoginFailedMessage_Text {
            get {
                return ResourceManager.GetString("lblLoginFailedMessage.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to False.
        /// </summary>
        internal static bool lblLoginFailedMessage_Visible {
            get {
                object obj = ResourceManager.GetObject("lblLoginFailedMessage.Visible", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to True.
        /// </summary>
        internal static bool lblPassword_AutoSize {
            get {
                object obj = ResourceManager.GetObject("lblPassword.AutoSize", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Windows.Forms.ImeMode similar to NoControl.
        /// </summary>
        internal static System.Windows.Forms.ImeMode lblPassword_ImeMode {
            get {
                object obj = ResourceManager.GetObject("lblPassword.ImeMode", resourceCulture);
                return ((System.Windows.Forms.ImeMode)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=328,Y=247}.
        /// </summary>
        internal static System.Drawing.Point lblPassword_Location {
            get {
                object obj = ResourceManager.GetObject("lblPassword.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=53, Height=13}.
        /// </summary>
        internal static System.Drawing.Size lblPassword_Size {
            get {
                object obj = ResourceManager.GetObject("lblPassword.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 3.
        /// </summary>
        internal static int lblPassword_TabIndex {
            get {
                object obj = ResourceManager.GetObject("lblPassword.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string lblPassword_Text {
            get {
                return ResourceManager.GetString("lblPassword.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to True.
        /// </summary>
        internal static bool lblUsername_AutoSize {
            get {
                object obj = ResourceManager.GetObject("lblUsername.AutoSize", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=326,Y=201}.
        /// </summary>
        internal static System.Drawing.Point lblUsername_Location {
            get {
                object obj = ResourceManager.GetObject("lblUsername.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=55, Height=13}.
        /// </summary>
        internal static System.Drawing.Size lblUsername_Size {
            get {
                object obj = ResourceManager.GetObject("lblUsername.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 2.
        /// </summary>
        internal static int lblUsername_TabIndex {
            get {
                object obj = ResourceManager.GetObject("lblUsername.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        internal static string lblUsername_Text {
            get {
                return ResourceManager.GetString("lblUsername.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Fill In All Information.
        /// </summary>
        internal static string loginFailedMsg {
            get {
                return ResourceManager.GetString("loginFailedMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=387,Y=244}.
        /// </summary>
        internal static System.Drawing.Point tbPassword_Location {
            get {
                object obj = ResourceManager.GetObject("tbPassword.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=100, Height=20}.
        /// </summary>
        internal static System.Drawing.Size tbPassword_Size {
            get {
                object obj = ResourceManager.GetObject("tbPassword.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 1.
        /// </summary>
        internal static int tbPassword_TabIndex {
            get {
                object obj = ResourceManager.GetObject("tbPassword.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=387,Y=198}.
        /// </summary>
        internal static System.Drawing.Point tbUsername_Location {
            get {
                object obj = ResourceManager.GetObject("tbUsername.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=100, Height=20}.
        /// </summary>
        internal static System.Drawing.Size tbUsername_Size {
            get {
                object obj = ResourceManager.GetObject("tbUsername.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 0.
        /// </summary>
        internal static int tbUsername_TabIndex {
            get {
                object obj = ResourceManager.GetObject("tbUsername.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect Password.
        /// </summary>
        internal static string wrongPasswordMsg {
            get {
                return ResourceManager.GetString("wrongPasswordMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username or Password Not Found.
        /// </summary>
        internal static string wrongUsernameMsg {
            get {
                return ResourceManager.GetString("wrongUsernameMsg", resourceCulture);
            }
        }
    }
}
