//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Better_Limited_Project.Navigation.UI {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AdminNavigationForm_zh_HK {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AdminNavigationForm_zh_HK() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Better_Limited_Project.Navigation.UI.AdminNavigationForm.zh-HK", typeof(AdminNavigationForm_zh_HK).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 管理員
        ///.
        /// </summary>
        internal static string admin {
            get {
                return ResourceManager.GetString("admin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=40,Y=120}.
        /// </summary>
        internal static System.Drawing.Point btnCustomer_Location {
            get {
                object obj = ResourceManager.GetObject("btnCustomer.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=111, Height=34}.
        /// </summary>
        internal static System.Drawing.Size btnCustomer_Size {
            get {
                object obj = ResourceManager.GetObject("btnCustomer.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 33.
        /// </summary>
        internal static int btnCustomer_TabIndex {
            get {
                object obj = ResourceManager.GetObject("btnCustomer.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 顧客.
        /// </summary>
        internal static string btnCustomer_Text {
            get {
                return ResourceManager.GetString("btnCustomer.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=40,Y=200}.
        /// </summary>
        internal static System.Drawing.Point btnProductList_Location {
            get {
                object obj = ResourceManager.GetObject("btnProductList.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=111, Height=34}.
        /// </summary>
        internal static System.Drawing.Size btnProductList_Size {
            get {
                object obj = ResourceManager.GetObject("btnProductList.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 32.
        /// </summary>
        internal static int btnProductList_TabIndex {
            get {
                object obj = ResourceManager.GetObject("btnProductList.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 產品列表.
        /// </summary>
        internal static string btnProductList_Text {
            get {
                return ResourceManager.GetString("btnProductList.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Font similar to [Font: Name=Microsoft Sans Serif, Size=8.25, Units=3, GdiCharSet=1, GdiVerticalFont=False].
        /// </summary>
        internal static System.Drawing.Font btnProfile_Font {
            get {
                object obj = ResourceManager.GetObject("btnProfile.Font", resourceCulture);
                return ((System.Drawing.Font)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=12,Y=55}.
        /// </summary>
        internal static System.Drawing.Point btnProfile_Location {
            get {
                object obj = ResourceManager.GetObject("btnProfile.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=164, Height=48}.
        /// </summary>
        internal static System.Drawing.Size btnProfile_Size {
            get {
                object obj = ResourceManager.GetObject("btnProfile.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 28.
        /// </summary>
        internal static int btnProfile_TabIndex {
            get {
                object obj = ResourceManager.GetObject("btnProfile.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Name).
        /// </summary>
        internal static string btnProfile_Text {
            get {
                return ResourceManager.GetString("btnProfile.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=40,Y=280}.
        /// </summary>
        internal static System.Drawing.Point btnSettings_Location {
            get {
                object obj = ResourceManager.GetObject("btnSettings.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=111, Height=34}.
        /// </summary>
        internal static System.Drawing.Size btnSettings_Size {
            get {
                object obj = ResourceManager.GetObject("btnSettings.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 26.
        /// </summary>
        internal static int btnSettings_TabIndex {
            get {
                object obj = ResourceManager.GetObject("btnSettings.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 設定.
        /// </summary>
        internal static string btnSettings_Text {
            get {
                return ResourceManager.GetString("btnSettings.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=40,Y=160}.
        /// </summary>
        internal static System.Drawing.Point btnStaff_Location {
            get {
                object obj = ResourceManager.GetObject("btnStaff.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=111, Height=34}.
        /// </summary>
        internal static System.Drawing.Size btnStaff_Size {
            get {
                object obj = ResourceManager.GetObject("btnStaff.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 24.
        /// </summary>
        internal static int btnStaff_TabIndex {
            get {
                object obj = ResourceManager.GetObject("btnStaff.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 員工.
        /// </summary>
        internal static string btnStaff_Text {
            get {
                return ResourceManager.GetString("btnStaff.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=40,Y=240}.
        /// </summary>
        internal static System.Drawing.Point btnSupplier_Location {
            get {
                object obj = ResourceManager.GetObject("btnSupplier.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=111, Height=34}.
        /// </summary>
        internal static System.Drawing.Size btnSupplier_Size {
            get {
                object obj = ResourceManager.GetObject("btnSupplier.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 27.
        /// </summary>
        internal static int btnSupplier_TabIndex {
            get {
                object obj = ResourceManager.GetObject("btnSupplier.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 供應商.
        /// </summary>
        internal static string btnSupplier_Text {
            get {
                return ResourceManager.GetString("btnSupplier.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 管理員模式
        ///.
        /// </summary>
        internal static string lblAdminMode_Text {
            get {
                return ResourceManager.GetString("lblAdminMode.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 登入為.
        /// </summary>
        internal static string lblLoggedIn_Text {
            get {
                return ResourceManager.GetString("lblLoggedIn.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Font similar to [Font: Name=Microsoft Sans Serif, Size=12, Units=3, GdiCharSet=1, GdiVerticalFont=False].
        /// </summary>
        internal static System.Drawing.Font lblLoggedInAs_Font {
            get {
                object obj = ResourceManager.GetObject("lblLoggedInAs.Font", resourceCulture);
                return ((System.Drawing.Font)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=27,Y=9}.
        /// </summary>
        internal static System.Drawing.Point lblLoggedInAs_Location {
            get {
                object obj = ResourceManager.GetObject("lblLoggedInAs.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=135, Height=43}.
        /// </summary>
        internal static System.Drawing.Size lblLoggedInAs_Size {
            get {
                object obj = ResourceManager.GetObject("lblLoggedInAs.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 29.
        /// </summary>
        internal static int lblLoggedInAs_TabIndex {
            get {
                object obj = ResourceManager.GetObject("lblLoggedInAs.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.ContentAlignment similar to MiddleCenter.
        /// </summary>
        internal static System.Drawing.ContentAlignment lblLoggedInAs_TextAlign {
            get {
                object obj = ResourceManager.GetObject("lblLoggedInAs.TextAlign", resourceCulture);
                return ((System.Drawing.ContentAlignment)(obj));
            }
        }
    }
}
