//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Better_Limited_Project.CustomerRecord {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CreateCustomerRecordForm_zh_HK {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CreateCustomerRecordForm_zh_HK() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Better_Limited_Project.CustomerRecord.CreateCustomerRecordForm.zh-HK", typeof(CreateCustomerRecordForm_zh_HK).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Font similar to [Font: Name=Microsoft Sans Serif, Size=12, Units=3, GdiCharSet=1, GdiVerticalFont=False].
        /// </summary>
        internal static System.Drawing.Font btnCreate_Font {
            get {
                object obj = ResourceManager.GetObject("btnCreate.Font", resourceCulture);
                return ((System.Drawing.Font)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=228,Y=363}.
        /// </summary>
        internal static System.Drawing.Point btnCreate_Location {
            get {
                object obj = ResourceManager.GetObject("btnCreate.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=118, Height=52}.
        /// </summary>
        internal static System.Drawing.Size btnCreate_Size {
            get {
                object obj = ResourceManager.GetObject("btnCreate.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 107.
        /// </summary>
        internal static int btnCreate_TabIndex {
            get {
                object obj = ResourceManager.GetObject("btnCreate.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 創造.
        /// </summary>
        internal static string btnCreate_Text {
            get {
                return ResourceManager.GetString("btnCreate.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 請輸入所有必填資料.
        /// </summary>
        internal static string hasUnfilledRequiredFieldsMessage {
            get {
                return ResourceManager.GetString("hasUnfilledRequiredFieldsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 無效的郵件地址。 請輸入有效的電子郵件地址或將其留空。.
        /// </summary>
        internal static string invalidEmailMessage {
            get {
                return ResourceManager.GetString("invalidEmailMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 無效的電話號碼。 請輸入 8 位數的香港電話號碼。 例如12345678。.
        /// </summary>
        internal static string invalidPhoneNumberMessage {
            get {
                return ResourceManager.GetString("invalidPhoneNumberMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to True.
        /// </summary>
        internal static bool lblAddress1_AutoSize {
            get {
                object obj = ResourceManager.GetObject("lblAddress1.AutoSize", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Font similar to [Font: Name=Microsoft Sans Serif, Size=9.75, Units=3, GdiCharSet=1, GdiVerticalFont=False].
        /// </summary>
        internal static System.Drawing.Font lblAddress1_Font {
            get {
                object obj = ResourceManager.GetObject("lblAddress1.Font", resourceCulture);
                return ((System.Drawing.Font)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=315,Y=137}.
        /// </summary>
        internal static System.Drawing.Point lblAddress1_Location {
            get {
                object obj = ResourceManager.GetObject("lblAddress1.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=69, Height=16}.
        /// </summary>
        internal static System.Drawing.Size lblAddress1_Size {
            get {
                object obj = ResourceManager.GetObject("lblAddress1.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 17.
        /// </summary>
        internal static int lblAddress1_TabIndex {
            get {
                object obj = ResourceManager.GetObject("lblAddress1.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 地址1.
        /// </summary>
        internal static string lblAddress1_Text {
            get {
                return ResourceManager.GetString("lblAddress1.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to True.
        /// </summary>
        internal static bool lblAddress2_AutoSize {
            get {
                object obj = ResourceManager.GetObject("lblAddress2.AutoSize", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Font similar to [Font: Name=Microsoft Sans Serif, Size=9.75, Units=3, GdiCharSet=1, GdiVerticalFont=False].
        /// </summary>
        internal static System.Drawing.Font lblAddress2_Font {
            get {
                object obj = ResourceManager.GetObject("lblAddress2.Font", resourceCulture);
                return ((System.Drawing.Font)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=315,Y=246}.
        /// </summary>
        internal static System.Drawing.Point lblAddress2_Location {
            get {
                object obj = ResourceManager.GetObject("lblAddress2.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=69, Height=16}.
        /// </summary>
        internal static System.Drawing.Size lblAddress2_Size {
            get {
                object obj = ResourceManager.GetObject("lblAddress2.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 18.
        /// </summary>
        internal static int lblAddress2_TabIndex {
            get {
                object obj = ResourceManager.GetObject("lblAddress2.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 地址2.
        /// </summary>
        internal static string lblAddress2_Text {
            get {
                return ResourceManager.GetString("lblAddress2.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to True.
        /// </summary>
        internal static bool lblCustName_AutoSize {
            get {
                object obj = ResourceManager.GetObject("lblCustName.AutoSize", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Font similar to [Font: Name=Microsoft Sans Serif, Size=9.75, Units=3, GdiCharSet=1, GdiVerticalFont=False].
        /// </summary>
        internal static System.Drawing.Font lblCustName_Font {
            get {
                object obj = ResourceManager.GetObject("lblCustName.Font", resourceCulture);
                return ((System.Drawing.Font)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=41,Y=137}.
        /// </summary>
        internal static System.Drawing.Point lblCustName_Location {
            get {
                object obj = ResourceManager.GetObject("lblCustName.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=45, Height=16}.
        /// </summary>
        internal static System.Drawing.Size lblCustName_Size {
            get {
                object obj = ResourceManager.GetObject("lblCustName.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 10.
        /// </summary>
        internal static int lblCustName_TabIndex {
            get {
                object obj = ResourceManager.GetObject("lblCustName.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 姓名.
        /// </summary>
        internal static string lblCustName_Text {
            get {
                return ResourceManager.GetString("lblCustName.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to True.
        /// </summary>
        internal static bool lblCustomerInfo_AutoSize {
            get {
                object obj = ResourceManager.GetObject("lblCustomerInfo.AutoSize", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Font similar to [Font: Name=Microsoft Sans Serif, Size=12, Units=3, GdiCharSet=1, GdiVerticalFont=False].
        /// </summary>
        internal static System.Drawing.Font lblCustomerInfo_Font {
            get {
                object obj = ResourceManager.GetObject("lblCustomerInfo.Font", resourceCulture);
                return ((System.Drawing.Font)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=87,Y=96}.
        /// </summary>
        internal static System.Drawing.Point lblCustomerInfo_Location {
            get {
                object obj = ResourceManager.GetObject("lblCustomerInfo.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=123, Height=20}.
        /// </summary>
        internal static System.Drawing.Size lblCustomerInfo_Size {
            get {
                object obj = ResourceManager.GetObject("lblCustomerInfo.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 9.
        /// </summary>
        internal static int lblCustomerInfo_TabIndex {
            get {
                object obj = ResourceManager.GetObject("lblCustomerInfo.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 顧客資料.
        /// </summary>
        internal static string lblCustomerInfo_Text {
            get {
                return ResourceManager.GetString("lblCustomerInfo.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to True.
        /// </summary>
        internal static bool lblCustPhoneNumber_AutoSize {
            get {
                object obj = ResourceManager.GetObject("lblCustPhoneNumber.AutoSize", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Font similar to [Font: Name=Microsoft Sans Serif, Size=9.75, Units=3, GdiCharSet=1, GdiVerticalFont=False].
        /// </summary>
        internal static System.Drawing.Font lblCustPhoneNumber_Font {
            get {
                object obj = ResourceManager.GetObject("lblCustPhoneNumber.Font", resourceCulture);
                return ((System.Drawing.Font)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=41,Y=205}.
        /// </summary>
        internal static System.Drawing.Point lblCustPhoneNumber_Location {
            get {
                object obj = ResourceManager.GetObject("lblCustPhoneNumber.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=98, Height=16}.
        /// </summary>
        internal static System.Drawing.Size lblCustPhoneNumber_Size {
            get {
                object obj = ResourceManager.GetObject("lblCustPhoneNumber.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 11.
        /// </summary>
        internal static int lblCustPhoneNumber_TabIndex {
            get {
                object obj = ResourceManager.GetObject("lblCustPhoneNumber.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 電話號碼.
        /// </summary>
        internal static string lblCustPhoneNumber_Text {
            get {
                return ResourceManager.GetString("lblCustPhoneNumber.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to True.
        /// </summary>
        internal static bool lblDeliveryInfo_AutoSize {
            get {
                object obj = ResourceManager.GetObject("lblDeliveryInfo.AutoSize", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Font similar to [Font: Name=Microsoft Sans Serif, Size=12, Units=3, GdiCharSet=1, GdiVerticalFont=False].
        /// </summary>
        internal static System.Drawing.Font lblDeliveryInfo_Font {
            get {
                object obj = ResourceManager.GetObject("lblDeliveryInfo.Font", resourceCulture);
                return ((System.Drawing.Font)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=367,Y=96}.
        /// </summary>
        internal static System.Drawing.Point lblDeliveryInfo_Location {
            get {
                object obj = ResourceManager.GetObject("lblDeliveryInfo.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=109, Height=20}.
        /// </summary>
        internal static System.Drawing.Size lblDeliveryInfo_Size {
            get {
                object obj = ResourceManager.GetObject("lblDeliveryInfo.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 16.
        /// </summary>
        internal static int lblDeliveryInfo_TabIndex {
            get {
                object obj = ResourceManager.GetObject("lblDeliveryInfo.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 送貨資訊.
        /// </summary>
        internal static string lblDeliveryInfo_Text {
            get {
                return ResourceManager.GetString("lblDeliveryInfo.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to True.
        /// </summary>
        internal static bool lblEmailAddress_AutoSize {
            get {
                object obj = ResourceManager.GetObject("lblEmailAddress.AutoSize", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Font similar to [Font: Name=Microsoft Sans Serif, Size=9.75, Units=3, GdiCharSet=1, GdiVerticalFont=False].
        /// </summary>
        internal static System.Drawing.Font lblEmailAddress_Font {
            get {
                object obj = ResourceManager.GetObject("lblEmailAddress.Font", resourceCulture);
                return ((System.Drawing.Font)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=41,Y=276}.
        /// </summary>
        internal static System.Drawing.Point lblEmailAddress_Location {
            get {
                object obj = ResourceManager.GetObject("lblEmailAddress.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=157, Height=16}.
        /// </summary>
        internal static System.Drawing.Size lblEmailAddress_Size {
            get {
                object obj = ResourceManager.GetObject("lblEmailAddress.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 12.
        /// </summary>
        internal static int lblEmailAddress_TabIndex {
            get {
                object obj = ResourceManager.GetObject("lblEmailAddress.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 電子郵件地址（可不填）.
        /// </summary>
        internal static string lblEmailAddress_Text {
            get {
                return ResourceManager.GetString("lblEmailAddress.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 新顧客記錄.
        /// </summary>
        internal static string lblHeader_Text {
            get {
                return ResourceManager.GetString("lblHeader.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to True.
        /// </summary>
        internal static bool lblRemind_AutoSize {
            get {
                object obj = ResourceManager.GetObject("lblRemind.AutoSize", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Font similar to [Font: Name=Microsoft Sans Serif, Size=16, Units=3, GdiCharSet=1, GdiVerticalFont=False].
        /// </summary>
        internal static System.Drawing.Font lblRemind_Font {
            get {
                object obj = ResourceManager.GetObject("lblRemind.Font", resourceCulture);
                return ((System.Drawing.Font)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=149,Y=30}.
        /// </summary>
        internal static System.Drawing.Point lblRemind_Location {
            get {
                object obj = ResourceManager.GetObject("lblRemind.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=276, Height=26}.
        /// </summary>
        internal static System.Drawing.Size lblRemind_Size {
            get {
                object obj = ResourceManager.GetObject("lblRemind.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 108.
        /// </summary>
        internal static int lblRemind_TabIndex {
            get {
                object obj = ResourceManager.GetObject("lblRemind.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=318,Y=165}.
        /// </summary>
        internal static System.Drawing.Point txtAddress1_Location {
            get {
                object obj = ResourceManager.GetObject("txtAddress1.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to True.
        /// </summary>
        internal static bool txtAddress1_Multiline {
            get {
                object obj = ResourceManager.GetObject("txtAddress1.Multiline", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=214, Height=50}.
        /// </summary>
        internal static System.Drawing.Size txtAddress1_Size {
            get {
                object obj = ResourceManager.GetObject("txtAddress1.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 20.
        /// </summary>
        internal static int txtAddress1_TabIndex {
            get {
                object obj = ResourceManager.GetObject("txtAddress1.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=318,Y=274}.
        /// </summary>
        internal static System.Drawing.Point txtAddress2_Location {
            get {
                object obj = ResourceManager.GetObject("txtAddress2.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to True.
        /// </summary>
        internal static bool txtAddress2_Multiline {
            get {
                object obj = ResourceManager.GetObject("txtAddress2.Multiline", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=214, Height=50}.
        /// </summary>
        internal static System.Drawing.Size txtAddress2_Size {
            get {
                object obj = ResourceManager.GetObject("txtAddress2.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 21.
        /// </summary>
        internal static int txtAddress2_TabIndex {
            get {
                object obj = ResourceManager.GetObject("txtAddress2.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=44,Y=165}.
        /// </summary>
        internal static System.Drawing.Point txtCustName_Location {
            get {
                object obj = ResourceManager.GetObject("txtCustName.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=214, Height=20}.
        /// </summary>
        internal static System.Drawing.Size txtCustName_Size {
            get {
                object obj = ResourceManager.GetObject("txtCustName.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 13.
        /// </summary>
        internal static int txtCustName_TabIndex {
            get {
                object obj = ResourceManager.GetObject("txtCustName.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=214, Height=20}.
        /// </summary>
        internal static System.Drawing.Size txtCustPhoneNumber_Size {
            get {
                object obj = ResourceManager.GetObject("txtCustPhoneNumber.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 14.
        /// </summary>
        internal static int txtCustPhoneNumber_TabIndex {
            get {
                object obj = ResourceManager.GetObject("txtCustPhoneNumber.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=44,Y=304}.
        /// </summary>
        internal static System.Drawing.Point txtEmailAddress_Location {
            get {
                object obj = ResourceManager.GetObject("txtEmailAddress.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=214, Height=20}.
        /// </summary>
        internal static System.Drawing.Size txtEmailAddress_Size {
            get {
                object obj = ResourceManager.GetObject("txtEmailAddress.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 15.
        /// </summary>
        internal static int txtEmailAddress_TabIndex {
            get {
                object obj = ResourceManager.GetObject("txtEmailAddress.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
    }
}
