//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Better_Limited_Project.CustomerRecord {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CustomerUpdateForm_zh_HK {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CustomerUpdateForm_zh_HK() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Better_Limited_Project.CustomerRecord.CustomerUpdateForm.zh-HK", typeof(CustomerUpdateForm_zh_HK).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Font similar to [Font: Name=Microsoft Sans Serif, Size=12, Units=3, GdiCharSet=1, GdiVerticalFont=False].
        /// </summary>
        internal static System.Drawing.Font btnUpdateInfo_Font {
            get {
                object obj = ResourceManager.GetObject("btnUpdateInfo.Font", resourceCulture);
                return ((System.Drawing.Font)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=308,Y=378}.
        /// </summary>
        internal static System.Drawing.Point btnUpdateInfo_Location {
            get {
                object obj = ResourceManager.GetObject("btnUpdateInfo.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=183, Height=44}.
        /// </summary>
        internal static System.Drawing.Size btnUpdateInfo_Size {
            get {
                object obj = ResourceManager.GetObject("btnUpdateInfo.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 66.
        /// </summary>
        internal static int btnUpdateInfo_TabIndex {
            get {
                object obj = ResourceManager.GetObject("btnUpdateInfo.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 更新資料.
        /// </summary>
        internal static string btnUpdateInfo_Text {
            get {
                return ResourceManager.GetString("btnUpdateInfo.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 請輸入所有必填資料.
        /// </summary>
        internal static string hasUnfilledRequiredFields {
            get {
                return ResourceManager.GetString("hasUnfilledRequiredFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 無效的郵件地址。 請輸入有效的電子郵件地址或將其留空。.
        /// </summary>
        internal static string invalidEmailAddressMessage {
            get {
                return ResourceManager.GetString("invalidEmailAddressMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 無效的電話號碼。 請輸入 8 位數的香港電話號碼。 例如 12345678。.
        /// </summary>
        internal static string invalidPhoneNumberMessage {
            get {
                return ResourceManager.GetString("invalidPhoneNumberMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to True.
        /// </summary>
        internal static bool lblAddress1_AutoSize {
            get {
                object obj = ResourceManager.GetObject("lblAddress1.AutoSize", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Font similar to [Font: Name=Microsoft Sans Serif, Size=9, Units=3, GdiCharSet=1, GdiVerticalFont=False].
        /// </summary>
        internal static System.Drawing.Font lblAddress1_Font {
            get {
                object obj = ResourceManager.GetObject("lblAddress1.Font", resourceCulture);
                return ((System.Drawing.Font)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=76,Y=265}.
        /// </summary>
        internal static System.Drawing.Point lblAddress1_Location {
            get {
                object obj = ResourceManager.GetObject("lblAddress1.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=64, Height=15}.
        /// </summary>
        internal static System.Drawing.Size lblAddress1_Size {
            get {
                object obj = ResourceManager.GetObject("lblAddress1.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 117.
        /// </summary>
        internal static int lblAddress1_TabIndex {
            get {
                object obj = ResourceManager.GetObject("lblAddress1.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 地址1:.
        /// </summary>
        internal static string lblAddress1_Text {
            get {
                return ResourceManager.GetString("lblAddress1.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to True.
        /// </summary>
        internal static bool lblAddress2_AutoSize {
            get {
                object obj = ResourceManager.GetObject("lblAddress2.AutoSize", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Font similar to [Font: Name=Microsoft Sans Serif, Size=9, Units=3, GdiCharSet=1, GdiVerticalFont=False].
        /// </summary>
        internal static System.Drawing.Font lblAddress2_Font {
            get {
                object obj = ResourceManager.GetObject("lblAddress2.Font", resourceCulture);
                return ((System.Drawing.Font)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=76,Y=302}.
        /// </summary>
        internal static System.Drawing.Point lblAddress2_Location {
            get {
                object obj = ResourceManager.GetObject("lblAddress2.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=64, Height=15}.
        /// </summary>
        internal static System.Drawing.Size lblAddress2_Size {
            get {
                object obj = ResourceManager.GetObject("lblAddress2.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 119.
        /// </summary>
        internal static int lblAddress2_TabIndex {
            get {
                object obj = ResourceManager.GetObject("lblAddress2.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 地址2:.
        /// </summary>
        internal static string lblAddress2_Text {
            get {
                return ResourceManager.GetString("lblAddress2.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to True.
        /// </summary>
        internal static bool lblEmail_AutoSize {
            get {
                object obj = ResourceManager.GetObject("lblEmail.AutoSize", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Font similar to [Font: Name=Microsoft Sans Serif, Size=9, Units=3, GdiCharSet=1, GdiVerticalFont=False].
        /// </summary>
        internal static System.Drawing.Font lblEmail_Font {
            get {
                object obj = ResourceManager.GetObject("lblEmail.Font", resourceCulture);
                return ((System.Drawing.Font)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=51,Y=226}.
        /// </summary>
        internal static System.Drawing.Point lblEmail_Location {
            get {
                object obj = ResourceManager.GetObject("lblEmail.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=89, Height=15}.
        /// </summary>
        internal static System.Drawing.Size lblEmail_Size {
            get {
                object obj = ResourceManager.GetObject("lblEmail.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 113.
        /// </summary>
        internal static int lblEmail_TabIndex {
            get {
                object obj = ResourceManager.GetObject("lblEmail.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 電子郵件地址.
        /// </summary>
        internal static string lblEmail_Text {
            get {
                return ResourceManager.GetString("lblEmail.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to True.
        /// </summary>
        internal static bool lblHeader_AutoSize {
            get {
                object obj = ResourceManager.GetObject("lblHeader.AutoSize", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Font similar to [Font: Name=Microsoft Sans Serif, Size=15.75, Units=3, GdiCharSet=1, GdiVerticalFont=False].
        /// </summary>
        internal static System.Drawing.Font lblHeader_Font {
            get {
                object obj = ResourceManager.GetObject("lblHeader.Font", resourceCulture);
                return ((System.Drawing.Font)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=239,Y=34}.
        /// </summary>
        internal static System.Drawing.Point lblHeader_Location {
            get {
                object obj = ResourceManager.GetObject("lblHeader.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=318, Height=25}.
        /// </summary>
        internal static System.Drawing.Size lblHeader_Size {
            get {
                object obj = ResourceManager.GetObject("lblHeader.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 78.
        /// </summary>
        internal static int lblHeader_TabIndex {
            get {
                object obj = ResourceManager.GetObject("lblHeader.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 更新顧客資料.
        /// </summary>
        internal static string lblHeader_Text {
            get {
                return ResourceManager.GetString("lblHeader.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to True.
        /// </summary>
        internal static bool lblName_AutoSize {
            get {
                object obj = ResourceManager.GetObject("lblName.AutoSize", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Font similar to [Font: Name=Microsoft Sans Serif, Size=9, Units=3, GdiCharSet=1, GdiVerticalFont=False].
        /// </summary>
        internal static System.Drawing.Font lblName_Font {
            get {
                object obj = ResourceManager.GetObject("lblName.Font", resourceCulture);
                return ((System.Drawing.Font)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=96,Y=149}.
        /// </summary>
        internal static System.Drawing.Point lblName_Location {
            get {
                object obj = ResourceManager.GetObject("lblName.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=44, Height=15}.
        /// </summary>
        internal static System.Drawing.Size lblName_Size {
            get {
                object obj = ResourceManager.GetObject("lblName.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 111.
        /// </summary>
        internal static int lblName_TabIndex {
            get {
                object obj = ResourceManager.GetObject("lblName.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 姓名:.
        /// </summary>
        internal static string lblName_Text {
            get {
                return ResourceManager.GetString("lblName.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to True.
        /// </summary>
        internal static bool lblNewAddress1_AutoSize {
            get {
                object obj = ResourceManager.GetObject("lblNewAddress1.AutoSize", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Font similar to [Font: Name=Microsoft Sans Serif, Size=9, Units=3, GdiCharSet=1, GdiVerticalFont=False].
        /// </summary>
        internal static System.Drawing.Font lblNewAddress1_Font {
            get {
                object obj = ResourceManager.GetObject("lblNewAddress1.Font", resourceCulture);
                return ((System.Drawing.Font)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=432,Y=266}.
        /// </summary>
        internal static System.Drawing.Point lblNewAddress1_Location {
            get {
                object obj = ResourceManager.GetObject("lblNewAddress1.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=64, Height=15}.
        /// </summary>
        internal static System.Drawing.Size lblNewAddress1_Size {
            get {
                object obj = ResourceManager.GetObject("lblNewAddress1.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 128.
        /// </summary>
        internal static int lblNewAddress1_TabIndex {
            get {
                object obj = ResourceManager.GetObject("lblNewAddress1.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 地址1:.
        /// </summary>
        internal static string lblNewAddress1_Text {
            get {
                return ResourceManager.GetString("lblNewAddress1.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to True.
        /// </summary>
        internal static bool lblNewAddress2_AutoSize {
            get {
                object obj = ResourceManager.GetObject("lblNewAddress2.AutoSize", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Font similar to [Font: Name=Microsoft Sans Serif, Size=9, Units=3, GdiCharSet=1, GdiVerticalFont=False].
        /// </summary>
        internal static System.Drawing.Font lblNewAddress2_Font {
            get {
                object obj = ResourceManager.GetObject("lblNewAddress2.Font", resourceCulture);
                return ((System.Drawing.Font)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=430,Y=303}.
        /// </summary>
        internal static System.Drawing.Point lblNewAddress2_Location {
            get {
                object obj = ResourceManager.GetObject("lblNewAddress2.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=64, Height=15}.
        /// </summary>
        internal static System.Drawing.Size lblNewAddress2_Size {
            get {
                object obj = ResourceManager.GetObject("lblNewAddress2.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 130.
        /// </summary>
        internal static int lblNewAddress2_TabIndex {
            get {
                object obj = ResourceManager.GetObject("lblNewAddress2.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 地址2:.
        /// </summary>
        internal static string lblNewAddress2_Text {
            get {
                return ResourceManager.GetString("lblNewAddress2.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to True.
        /// </summary>
        internal static bool lblNewEmail_AutoSize {
            get {
                object obj = ResourceManager.GetObject("lblNewEmail.AutoSize", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Font similar to [Font: Name=Microsoft Sans Serif, Size=9, Units=3, GdiCharSet=1, GdiVerticalFont=False].
        /// </summary>
        internal static System.Drawing.Font lblNewEmail_Font {
            get {
                object obj = ResourceManager.GetObject("lblNewEmail.Font", resourceCulture);
                return ((System.Drawing.Font)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=407,Y=227}.
        /// </summary>
        internal static System.Drawing.Point lblNewEmail_Location {
            get {
                object obj = ResourceManager.GetObject("lblNewEmail.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=89, Height=15}.
        /// </summary>
        internal static System.Drawing.Size lblNewEmail_Size {
            get {
                object obj = ResourceManager.GetObject("lblNewEmail.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 124.
        /// </summary>
        internal static int lblNewEmail_TabIndex {
            get {
                object obj = ResourceManager.GetObject("lblNewEmail.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 電子郵件地址.
        /// </summary>
        internal static string lblNewEmail_Text {
            get {
                return ResourceManager.GetString("lblNewEmail.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to True.
        /// </summary>
        internal static bool lblNewInfo_AutoSize {
            get {
                object obj = ResourceManager.GetObject("lblNewInfo.AutoSize", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Font similar to [Font: Name=Microsoft Sans Serif, Size=12, Units=3, GdiCharSet=1, GdiVerticalFont=False].
        /// </summary>
        internal static System.Drawing.Font lblNewInfo_Font {
            get {
                object obj = ResourceManager.GetObject("lblNewInfo.Font", resourceCulture);
                return ((System.Drawing.Font)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=564,Y=97}.
        /// </summary>
        internal static System.Drawing.Point lblNewInfo_Location {
            get {
                object obj = ResourceManager.GetObject("lblNewInfo.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=80, Height=20}.
        /// </summary>
        internal static System.Drawing.Size lblNewInfo_Size {
            get {
                object obj = ResourceManager.GetObject("lblNewInfo.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 121.
        /// </summary>
        internal static int lblNewInfo_TabIndex {
            get {
                object obj = ResourceManager.GetObject("lblNewInfo.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 新資料.
        /// </summary>
        internal static string lblNewInfo_Text {
            get {
                return ResourceManager.GetString("lblNewInfo.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to True.
        /// </summary>
        internal static bool lblNewName_AutoSize {
            get {
                object obj = ResourceManager.GetObject("lblNewName.AutoSize", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Font similar to [Font: Name=Microsoft Sans Serif, Size=9, Units=3, GdiCharSet=1, GdiVerticalFont=False].
        /// </summary>
        internal static System.Drawing.Font lblNewName_Font {
            get {
                object obj = ResourceManager.GetObject("lblNewName.Font", resourceCulture);
                return ((System.Drawing.Font)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=452,Y=150}.
        /// </summary>
        internal static System.Drawing.Point lblNewName_Location {
            get {
                object obj = ResourceManager.GetObject("lblNewName.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=44, Height=15}.
        /// </summary>
        internal static System.Drawing.Size lblNewName_Size {
            get {
                object obj = ResourceManager.GetObject("lblNewName.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 122.
        /// </summary>
        internal static int lblNewName_TabIndex {
            get {
                object obj = ResourceManager.GetObject("lblNewName.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 姓名:.
        /// </summary>
        internal static string lblNewName_Text {
            get {
                return ResourceManager.GetString("lblNewName.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to True.
        /// </summary>
        internal static bool lblNewPhone_AutoSize {
            get {
                object obj = ResourceManager.GetObject("lblNewPhone.AutoSize", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Font similar to [Font: Name=Microsoft Sans Serif, Size=9, Units=3, GdiCharSet=1, GdiVerticalFont=False].
        /// </summary>
        internal static System.Drawing.Font lblNewPhone_Font {
            get {
                object obj = ResourceManager.GetObject("lblNewPhone.Font", resourceCulture);
                return ((System.Drawing.Font)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=450,Y=186}.
        /// </summary>
        internal static System.Drawing.Point lblNewPhone_Location {
            get {
                object obj = ResourceManager.GetObject("lblNewPhone.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=46, Height=15}.
        /// </summary>
        internal static System.Drawing.Size lblNewPhone_Size {
            get {
                object obj = ResourceManager.GetObject("lblNewPhone.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 126.
        /// </summary>
        internal static int lblNewPhone_TabIndex {
            get {
                object obj = ResourceManager.GetObject("lblNewPhone.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 電話號碼:.
        /// </summary>
        internal static string lblNewPhone_Text {
            get {
                return ResourceManager.GetString("lblNewPhone.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to True.
        /// </summary>
        internal static bool lblOriginalInfo_AutoSize {
            get {
                object obj = ResourceManager.GetObject("lblOriginalInfo.AutoSize", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Font similar to [Font: Name=Microsoft Sans Serif, Size=12, Units=3, GdiCharSet=1, GdiVerticalFont=False].
        /// </summary>
        internal static System.Drawing.Font lblOriginalInfo_Font {
            get {
                object obj = ResourceManager.GetObject("lblOriginalInfo.Font", resourceCulture);
                return ((System.Drawing.Font)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=208,Y=96}.
        /// </summary>
        internal static System.Drawing.Point lblOriginalInfo_Location {
            get {
                object obj = ResourceManager.GetObject("lblOriginalInfo.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=107, Height=20}.
        /// </summary>
        internal static System.Drawing.Size lblOriginalInfo_Size {
            get {
                object obj = ResourceManager.GetObject("lblOriginalInfo.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 57.
        /// </summary>
        internal static int lblOriginalInfo_TabIndex {
            get {
                object obj = ResourceManager.GetObject("lblOriginalInfo.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 原資料.
        /// </summary>
        internal static string lblOriginalInfo_Text {
            get {
                return ResourceManager.GetString("lblOriginalInfo.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to True.
        /// </summary>
        internal static bool lblPhone_AutoSize {
            get {
                object obj = ResourceManager.GetObject("lblPhone.AutoSize", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Font similar to [Font: Name=Microsoft Sans Serif, Size=9, Units=3, GdiCharSet=1, GdiVerticalFont=False].
        /// </summary>
        internal static System.Drawing.Font lblPhone_Font {
            get {
                object obj = ResourceManager.GetObject("lblPhone.Font", resourceCulture);
                return ((System.Drawing.Font)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=94,Y=185}.
        /// </summary>
        internal static System.Drawing.Point lblPhone_Location {
            get {
                object obj = ResourceManager.GetObject("lblPhone.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=46, Height=15}.
        /// </summary>
        internal static System.Drawing.Size lblPhone_Size {
            get {
                object obj = ResourceManager.GetObject("lblPhone.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 115.
        /// </summary>
        internal static int lblPhone_TabIndex {
            get {
                object obj = ResourceManager.GetObject("lblPhone.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 電話號碼:.
        /// </summary>
        internal static string lblPhone_Text {
            get {
                return ResourceManager.GetString("lblPhone.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 請填寫所有資料.
        /// </summary>
        internal static string loginFailedMessage {
            get {
                return ResourceManager.GetString("loginFailedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=146,Y=264}.
        /// </summary>
        internal static System.Drawing.Point tbAddress1_Location {
            get {
                object obj = ResourceManager.GetObject("tbAddress1.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=247, Height=20}.
        /// </summary>
        internal static System.Drawing.Size tbAddress1_Size {
            get {
                object obj = ResourceManager.GetObject("tbAddress1.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 118.
        /// </summary>
        internal static int tbAddress1_TabIndex {
            get {
                object obj = ResourceManager.GetObject("tbAddress1.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=146,Y=301}.
        /// </summary>
        internal static System.Drawing.Point tbAddress2_Location {
            get {
                object obj = ResourceManager.GetObject("tbAddress2.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=247, Height=20}.
        /// </summary>
        internal static System.Drawing.Size tbAddress2_Size {
            get {
                object obj = ResourceManager.GetObject("tbAddress2.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 120.
        /// </summary>
        internal static int tbAddress2_TabIndex {
            get {
                object obj = ResourceManager.GetObject("tbAddress2.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=146,Y=225}.
        /// </summary>
        internal static System.Drawing.Point tbEmailAddress_Location {
            get {
                object obj = ResourceManager.GetObject("tbEmailAddress.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=247, Height=20}.
        /// </summary>
        internal static System.Drawing.Size tbEmailAddress_Size {
            get {
                object obj = ResourceManager.GetObject("tbEmailAddress.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 114.
        /// </summary>
        internal static int tbEmailAddress_TabIndex {
            get {
                object obj = ResourceManager.GetObject("tbEmailAddress.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=146,Y=148}.
        /// </summary>
        internal static System.Drawing.Point tbname_Location {
            get {
                object obj = ResourceManager.GetObject("tbname.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=181, Height=20}.
        /// </summary>
        internal static System.Drawing.Size tbname_Size {
            get {
                object obj = ResourceManager.GetObject("tbname.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 112.
        /// </summary>
        internal static int tbname_TabIndex {
            get {
                object obj = ResourceManager.GetObject("tbname.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=502,Y=265}.
        /// </summary>
        internal static System.Drawing.Point tbNewAddress1_Location {
            get {
                object obj = ResourceManager.GetObject("tbNewAddress1.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=247, Height=20}.
        /// </summary>
        internal static System.Drawing.Size tbNewAddress1_Size {
            get {
                object obj = ResourceManager.GetObject("tbNewAddress1.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 4.
        /// </summary>
        internal static int tbNewAddress1_TabIndex {
            get {
                object obj = ResourceManager.GetObject("tbNewAddress1.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=502,Y=302}.
        /// </summary>
        internal static System.Drawing.Point tbNewAddress2_Location {
            get {
                object obj = ResourceManager.GetObject("tbNewAddress2.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=247, Height=20}.
        /// </summary>
        internal static System.Drawing.Size tbNewAddress2_Size {
            get {
                object obj = ResourceManager.GetObject("tbNewAddress2.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 5.
        /// </summary>
        internal static int tbNewAddress2_TabIndex {
            get {
                object obj = ResourceManager.GetObject("tbNewAddress2.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=502,Y=226}.
        /// </summary>
        internal static System.Drawing.Point tbNewEmail_Location {
            get {
                object obj = ResourceManager.GetObject("tbNewEmail.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=247, Height=20}.
        /// </summary>
        internal static System.Drawing.Size tbNewEmail_Size {
            get {
                object obj = ResourceManager.GetObject("tbNewEmail.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 3.
        /// </summary>
        internal static int tbNewEmail_TabIndex {
            get {
                object obj = ResourceManager.GetObject("tbNewEmail.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=502,Y=149}.
        /// </summary>
        internal static System.Drawing.Point tbNewName_Location {
            get {
                object obj = ResourceManager.GetObject("tbNewName.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=181, Height=20}.
        /// </summary>
        internal static System.Drawing.Size tbNewName_Size {
            get {
                object obj = ResourceManager.GetObject("tbNewName.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 1.
        /// </summary>
        internal static int tbNewName_TabIndex {
            get {
                object obj = ResourceManager.GetObject("tbNewName.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=502,Y=185}.
        /// </summary>
        internal static System.Drawing.Point tbNewPhone_Location {
            get {
                object obj = ResourceManager.GetObject("tbNewPhone.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=119, Height=20}.
        /// </summary>
        internal static System.Drawing.Size tbNewPhone_Size {
            get {
                object obj = ResourceManager.GetObject("tbNewPhone.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 2.
        /// </summary>
        internal static int tbNewPhone_TabIndex {
            get {
                object obj = ResourceManager.GetObject("tbNewPhone.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=146,Y=184}.
        /// </summary>
        internal static System.Drawing.Point tbPhone_Location {
            get {
                object obj = ResourceManager.GetObject("tbPhone.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=119, Height=20}.
        /// </summary>
        internal static System.Drawing.Size tbPhone_Size {
            get {
                object obj = ResourceManager.GetObject("tbPhone.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 116.
        /// </summary>
        internal static int tbPhone_TabIndex {
            get {
                object obj = ResourceManager.GetObject("tbPhone.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 未找到用戶名.
        /// </summary>
        internal static string usernameNotFoundMessage {
            get {
                return ResourceManager.GetString("usernameNotFoundMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 密碼錯誤.
        /// </summary>
        internal static string wrongPasswordMessage {
            get {
                return ResourceManager.GetString("wrongPasswordMessage", resourceCulture);
            }
        }
    }
}
