//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Better_Limited_Project.CustomerRecord {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    partial class CustomerDetailsForm {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Better_Limited_Project.CustomerRecord.CustomerDetailsForm", typeof(CustomerDetailsForm).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Font similar to [Font: Name=Microsoft Sans Serif, Size=12, Units=3, GdiCharSet=1, GdiVerticalFont=False].
        /// </summary>
        internal static System.Drawing.Font btnRemoveCustomer_Font {
            get {
                object obj = ResourceManager.GetObject("btnRemoveCustomer.Font", resourceCulture);
                return ((System.Drawing.Font)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=30,Y=370}.
        /// </summary>
        internal static System.Drawing.Point btnRemoveCustomer_Location {
            get {
                object obj = ResourceManager.GetObject("btnRemoveCustomer.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=177, Height=54}.
        /// </summary>
        internal static System.Drawing.Size btnRemoveCustomer_Size {
            get {
                object obj = ResourceManager.GetObject("btnRemoveCustomer.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 108.
        /// </summary>
        internal static int btnRemoveCustomer_TabIndex {
            get {
                object obj = ResourceManager.GetObject("btnRemoveCustomer.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Customer.
        /// </summary>
        internal static string btnRemoveCustomer_Text {
            get {
                return ResourceManager.GetString("btnRemoveCustomer.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Font similar to [Font: Name=Microsoft Sans Serif, Size=12, Units=3, GdiCharSet=1, GdiVerticalFont=False].
        /// </summary>
        internal static System.Drawing.Font btnUpdateInfo_Font {
            get {
                object obj = ResourceManager.GetObject("btnUpdateInfo.Font", resourceCulture);
                return ((System.Drawing.Font)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=314,Y=370}.
        /// </summary>
        internal static System.Drawing.Point btnUpdateInfo_Location {
            get {
                object obj = ResourceManager.GetObject("btnUpdateInfo.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=200, Height=54}.
        /// </summary>
        internal static System.Drawing.Size btnUpdateInfo_Size {
            get {
                object obj = ResourceManager.GetObject("btnUpdateInfo.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 87.
        /// </summary>
        internal static int btnUpdateInfo_TabIndex {
            get {
                object obj = ResourceManager.GetObject("btnUpdateInfo.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Customer Info.
        /// </summary>
        internal static string btnUpdateInfo_Text {
            get {
                return ResourceManager.GetString("btnUpdateInfo.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Windows.Forms.AnchorStyles similar to Right.
        /// </summary>
        internal static System.Windows.Forms.AnchorStyles lblAddress1_Anchor {
            get {
                object obj = ResourceManager.GetObject("lblAddress1.Anchor", resourceCulture);
                return ((System.Windows.Forms.AnchorStyles)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to True.
        /// </summary>
        internal static bool lblAddress1_AutoSize {
            get {
                object obj = ResourceManager.GetObject("lblAddress1.AutoSize", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Font similar to [Font: Name=Microsoft Sans Serif, Size=9, Units=3, GdiCharSet=1, GdiVerticalFont=False].
        /// </summary>
        internal static System.Drawing.Font lblAddress1_Font {
            get {
                object obj = ResourceManager.GetObject("lblAddress1.Font", resourceCulture);
                return ((System.Drawing.Font)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=372,Y=186}.
        /// </summary>
        internal static System.Drawing.Point lblAddress1_Location {
            get {
                object obj = ResourceManager.GetObject("lblAddress1.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=64, Height=15}.
        /// </summary>
        internal static System.Drawing.Size lblAddress1_Size {
            get {
                object obj = ResourceManager.GetObject("lblAddress1.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 101.
        /// </summary>
        internal static int lblAddress1_TabIndex {
            get {
                object obj = ResourceManager.GetObject("lblAddress1.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address 1:.
        /// </summary>
        internal static string lblAddress1_Text {
            get {
                return ResourceManager.GetString("lblAddress1.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Windows.Forms.AnchorStyles similar to Right.
        /// </summary>
        internal static System.Windows.Forms.AnchorStyles lblAddress2_Anchor {
            get {
                object obj = ResourceManager.GetObject("lblAddress2.Anchor", resourceCulture);
                return ((System.Windows.Forms.AnchorStyles)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to True.
        /// </summary>
        internal static bool lblAddress2_AutoSize {
            get {
                object obj = ResourceManager.GetObject("lblAddress2.AutoSize", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Font similar to [Font: Name=Microsoft Sans Serif, Size=9, Units=3, GdiCharSet=1, GdiVerticalFont=False].
        /// </summary>
        internal static System.Drawing.Font lblAddress2_Font {
            get {
                object obj = ResourceManager.GetObject("lblAddress2.Font", resourceCulture);
                return ((System.Drawing.Font)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=372,Y=223}.
        /// </summary>
        internal static System.Drawing.Point lblAddress2_Location {
            get {
                object obj = ResourceManager.GetObject("lblAddress2.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=64, Height=15}.
        /// </summary>
        internal static System.Drawing.Size lblAddress2_Size {
            get {
                object obj = ResourceManager.GetObject("lblAddress2.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 109.
        /// </summary>
        internal static int lblAddress2_TabIndex {
            get {
                object obj = ResourceManager.GetObject("lblAddress2.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address 2:.
        /// </summary>
        internal static string lblAddress2_Text {
            get {
                return ResourceManager.GetString("lblAddress2.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to True.
        /// </summary>
        internal static bool lblDeliveryAddress_AutoSize {
            get {
                object obj = ResourceManager.GetObject("lblDeliveryAddress.AutoSize", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Font similar to [Font: Name=Microsoft Sans Serif, Size=12, Units=3, GdiCharSet=1, GdiVerticalFont=False].
        /// </summary>
        internal static System.Drawing.Font lblDeliveryAddress_Font {
            get {
                object obj = ResourceManager.GetObject("lblDeliveryAddress.Font", resourceCulture);
                return ((System.Drawing.Font)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=465,Y=137}.
        /// </summary>
        internal static System.Drawing.Point lblDeliveryAddress_Location {
            get {
                object obj = ResourceManager.GetObject("lblDeliveryAddress.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=143, Height=20}.
        /// </summary>
        internal static System.Drawing.Size lblDeliveryAddress_Size {
            get {
                object obj = ResourceManager.GetObject("lblDeliveryAddress.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 99.
        /// </summary>
        internal static int lblDeliveryAddress_TabIndex {
            get {
                object obj = ResourceManager.GetObject("lblDeliveryAddress.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delivery Address.
        /// </summary>
        internal static string lblDeliveryAddress_Text {
            get {
                return ResourceManager.GetString("lblDeliveryAddress.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Windows.Forms.AnchorStyles similar to Right.
        /// </summary>
        internal static System.Windows.Forms.AnchorStyles lblEmail_Anchor {
            get {
                object obj = ResourceManager.GetObject("lblEmail.Anchor", resourceCulture);
                return ((System.Windows.Forms.AnchorStyles)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to True.
        /// </summary>
        internal static bool lblEmail_AutoSize {
            get {
                object obj = ResourceManager.GetObject("lblEmail.AutoSize", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Font similar to [Font: Name=Microsoft Sans Serif, Size=9, Units=3, GdiCharSet=1, GdiVerticalFont=False].
        /// </summary>
        internal static System.Drawing.Font lblEmail_Font {
            get {
                object obj = ResourceManager.GetObject("lblEmail.Font", resourceCulture);
                return ((System.Drawing.Font)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=86,Y=264}.
        /// </summary>
        internal static System.Drawing.Point lblEmail_Location {
            get {
                object obj = ResourceManager.GetObject("lblEmail.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=89, Height=15}.
        /// </summary>
        internal static System.Drawing.Size lblEmail_Size {
            get {
                object obj = ResourceManager.GetObject("lblEmail.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 93.
        /// </summary>
        internal static int lblEmail_TabIndex {
            get {
                object obj = ResourceManager.GetObject("lblEmail.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Address:.
        /// </summary>
        internal static string lblEmail_Text {
            get {
                return ResourceManager.GetString("lblEmail.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Windows.Forms.AnchorStyles similar to Top.
        /// </summary>
        internal static System.Windows.Forms.AnchorStyles lblHeader_Anchor {
            get {
                object obj = ResourceManager.GetObject("lblHeader.Anchor", resourceCulture);
                return ((System.Windows.Forms.AnchorStyles)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to True.
        /// </summary>
        internal static bool lblHeader_AutoSize {
            get {
                object obj = ResourceManager.GetObject("lblHeader.AutoSize", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Font similar to [Font: Name=Microsoft Sans Serif, Size=16, Units=3, GdiCharSet=1, GdiVerticalFont=False].
        /// </summary>
        internal static System.Drawing.Font lblHeader_Font {
            get {
                object obj = ResourceManager.GetObject("lblHeader.Font", resourceCulture);
                return ((System.Drawing.Font)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=284,Y=27}.
        /// </summary>
        internal static System.Drawing.Point lblHeader_Location {
            get {
                object obj = ResourceManager.GetObject("lblHeader.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=242, Height=26}.
        /// </summary>
        internal static System.Drawing.Size lblHeader_Size {
            get {
                object obj = ResourceManager.GetObject("lblHeader.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 90.
        /// </summary>
        internal static int lblHeader_TabIndex {
            get {
                object obj = ResourceManager.GetObject("lblHeader.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Information.
        /// </summary>
        internal static string lblHeader_Text {
            get {
                return ResourceManager.GetString("lblHeader.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.ContentAlignment similar to MiddleCenter.
        /// </summary>
        internal static System.Drawing.ContentAlignment lblHeader_TextAlign {
            get {
                object obj = ResourceManager.GetObject("lblHeader.TextAlign", resourceCulture);
                return ((System.Drawing.ContentAlignment)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Windows.Forms.AnchorStyles similar to Right.
        /// </summary>
        internal static System.Windows.Forms.AnchorStyles lblName_Anchor {
            get {
                object obj = ResourceManager.GetObject("lblName.Anchor", resourceCulture);
                return ((System.Windows.Forms.AnchorStyles)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to True.
        /// </summary>
        internal static bool lblName_AutoSize {
            get {
                object obj = ResourceManager.GetObject("lblName.AutoSize", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Font similar to [Font: Name=Microsoft Sans Serif, Size=9, Units=3, GdiCharSet=1, GdiVerticalFont=False].
        /// </summary>
        internal static System.Drawing.Font lblName_Font {
            get {
                object obj = ResourceManager.GetObject("lblName.Font", resourceCulture);
                return ((System.Drawing.Font)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=131,Y=187}.
        /// </summary>
        internal static System.Drawing.Point lblName_Location {
            get {
                object obj = ResourceManager.GetObject("lblName.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=44, Height=15}.
        /// </summary>
        internal static System.Drawing.Size lblName_Size {
            get {
                object obj = ResourceManager.GetObject("lblName.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 91.
        /// </summary>
        internal static int lblName_TabIndex {
            get {
                object obj = ResourceManager.GetObject("lblName.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name:.
        /// </summary>
        internal static string lblName_Text {
            get {
                return ResourceManager.GetString("lblName.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to True.
        /// </summary>
        internal static bool lblPersonalInfo_AutoSize {
            get {
                object obj = ResourceManager.GetObject("lblPersonalInfo.AutoSize", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Font similar to [Font: Name=Microsoft Sans Serif, Size=12, Units=3, GdiCharSet=1, GdiVerticalFont=False].
        /// </summary>
        internal static System.Drawing.Font lblPersonalInfo_Font {
            get {
                object obj = ResourceManager.GetObject("lblPersonalInfo.Font", resourceCulture);
                return ((System.Drawing.Font)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=113,Y=137}.
        /// </summary>
        internal static System.Drawing.Point lblPersonalInfo_Location {
            get {
                object obj = ResourceManager.GetObject("lblPersonalInfo.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=176, Height=20}.
        /// </summary>
        internal static System.Drawing.Size lblPersonalInfo_Size {
            get {
                object obj = ResourceManager.GetObject("lblPersonalInfo.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 84.
        /// </summary>
        internal static int lblPersonalInfo_TabIndex {
            get {
                object obj = ResourceManager.GetObject("lblPersonalInfo.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personal Information.
        /// </summary>
        internal static string lblPersonalInfo_Text {
            get {
                return ResourceManager.GetString("lblPersonalInfo.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Windows.Forms.AnchorStyles similar to Right.
        /// </summary>
        internal static System.Windows.Forms.AnchorStyles lblPhone_Anchor {
            get {
                object obj = ResourceManager.GetObject("lblPhone.Anchor", resourceCulture);
                return ((System.Windows.Forms.AnchorStyles)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to True.
        /// </summary>
        internal static bool lblPhone_AutoSize {
            get {
                object obj = ResourceManager.GetObject("lblPhone.AutoSize", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Font similar to [Font: Name=Microsoft Sans Serif, Size=9, Units=3, GdiCharSet=1, GdiVerticalFont=False].
        /// </summary>
        internal static System.Drawing.Font lblPhone_Font {
            get {
                object obj = ResourceManager.GetObject("lblPhone.Font", resourceCulture);
                return ((System.Drawing.Font)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=129,Y=223}.
        /// </summary>
        internal static System.Drawing.Point lblPhone_Location {
            get {
                object obj = ResourceManager.GetObject("lblPhone.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=46, Height=15}.
        /// </summary>
        internal static System.Drawing.Size lblPhone_Size {
            get {
                object obj = ResourceManager.GetObject("lblPhone.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 95.
        /// </summary>
        internal static int lblPhone_TabIndex {
            get {
                object obj = ResourceManager.GetObject("lblPhone.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone:.
        /// </summary>
        internal static string lblPhone_Text {
            get {
                return ResourceManager.GetString("lblPhone.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=442,Y=185}.
        /// </summary>
        internal static System.Drawing.Point tbAddress1_Location {
            get {
                object obj = ResourceManager.GetObject("tbAddress1.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=271, Height=20}.
        /// </summary>
        internal static System.Drawing.Size tbAddress1_Size {
            get {
                object obj = ResourceManager.GetObject("tbAddress1.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 103.
        /// </summary>
        internal static int tbAddress1_TabIndex {
            get {
                object obj = ResourceManager.GetObject("tbAddress1.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=442,Y=222}.
        /// </summary>
        internal static System.Drawing.Point tbAddress2_Location {
            get {
                object obj = ResourceManager.GetObject("tbAddress2.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=271, Height=20}.
        /// </summary>
        internal static System.Drawing.Size tbAddress2_Size {
            get {
                object obj = ResourceManager.GetObject("tbAddress2.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 110.
        /// </summary>
        internal static int tbAddress2_TabIndex {
            get {
                object obj = ResourceManager.GetObject("tbAddress2.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=181,Y=263}.
        /// </summary>
        internal static System.Drawing.Point tbEmailAddress_Location {
            get {
                object obj = ResourceManager.GetObject("tbEmailAddress.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=119, Height=20}.
        /// </summary>
        internal static System.Drawing.Size tbEmailAddress_Size {
            get {
                object obj = ResourceManager.GetObject("tbEmailAddress.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 94.
        /// </summary>
        internal static int tbEmailAddress_TabIndex {
            get {
                object obj = ResourceManager.GetObject("tbEmailAddress.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=181,Y=186}.
        /// </summary>
        internal static System.Drawing.Point tbname_Location {
            get {
                object obj = ResourceManager.GetObject("tbname.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=119, Height=20}.
        /// </summary>
        internal static System.Drawing.Size tbname_Size {
            get {
                object obj = ResourceManager.GetObject("tbname.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 92.
        /// </summary>
        internal static int tbname_TabIndex {
            get {
                object obj = ResourceManager.GetObject("tbname.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=181,Y=222}.
        /// </summary>
        internal static System.Drawing.Point tbPhone_Location {
            get {
                object obj = ResourceManager.GetObject("tbPhone.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=119, Height=20}.
        /// </summary>
        internal static System.Drawing.Size tbPhone_Size {
            get {
                object obj = ResourceManager.GetObject("tbPhone.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 96.
        /// </summary>
        internal static int tbPhone_TabIndex {
            get {
                object obj = ResourceManager.GetObject("tbPhone.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
    }
}
