//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Better_Limited_Project.ServiceUtility.Delivery {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class DeliveryStringResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DeliveryStringResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Better_Limited_Project.ServiceUtility.Delivery.DeliveryStringResources", typeof(DeliveryStringResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm setting delivery time along with dispatch time?.
        /// </summary>
        internal static string ask_confirm_setting_delivery_time {
            get {
                return ResourceManager.GetString("ask confirm setting delivery time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm setting dispatch time?.
        /// </summary>
        internal static string ask_setting_dispatch_time {
            get {
                return ResourceManager.GetString("ask setting dispatch time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delivery can only be arranged once the stock is replenished..
        /// </summary>
        internal static string cant_arrange_delivery_when_no_stock {
            get {
                return ResourceManager.GetString("cant arrange delivery when no stock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please choose at least one courier for this delivery..
        /// </summary>
        internal static string cant_choose_0_courier {
            get {
                return ResourceManager.GetString("cant choose 0 courier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sunday is company holiday and will not have deliveries. Please choose another day..
        /// </summary>
        internal static string cant_delivery_on_sunday {
            get {
                return ResourceManager.GetString("cant delivery on sunday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set Dispatch Time.
        /// </summary>
        internal static string set_dispatch_time {
            get {
                return ResourceManager.GetString("set dispatch time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set Time Delivered.
        /// </summary>
        internal static string set_time_delivered {
            get {
                return ResourceManager.GetString("set time delivered", resourceCulture);
            }
        }
    }
}
