//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Better_Limited_Project.ProductUtility {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ProductUtilityStringResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ProductUtilityStringResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Better_Limited_Project.ProductUtility.ProductUtilityStringResources", typeof(ProductUtilityStringResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm product removal?.
        /// </summary>
        internal static string ask_confirm_remove_product {
            get {
                return ResourceManager.GetString("ask confirm remove product", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Since this product is used in one or more sales orders, it will not be removed completely. This will remove all stock information for all retail stores/warehouses. Click ok to continue..
        /// </summary>
        internal static string cant_completely_remove_product_warning {
            get {
                return ResourceManager.GetString("cant completely remove product warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This product is used in one or more sales orders that has/have incomplete payments or deliveries which have not arrived. Product removal can only be done afterward. Product removal failed..
        /// </summary>
        internal static string cant_remove_product_message {
            get {
                return ResourceManager.GetString("cant remove product message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Removal.
        /// </summary>
        internal static string remove_product_confirm_dialog {
            get {
                return ResourceManager.GetString("remove product confirm dialog", resourceCulture);
            }
        }
    }
}
